server:
  build: .
  ports:
    - 3001:3000
  environment:
    - RDS_HOSTNAME=db
    - RDS_USERNAME=root
    - RDS_PASSWORD=my-secret-pw
    - RDS_PORT=3306
  links:
    - db:db

db:
  image: mysql:5
  ports:
    - 3306
  environment:
    - MYSQL_ROOT_PASSWORD=my-secret-pw
